### ISSUE TITLE
Fall back to self-signed certificate when no domain name is provided

### ISSUE THREAD

**Issue by winstonallo** [winstonallo/cloud-1#9]
```
- name: Configure certificates
  block:
    - name: Let's Encrypt
      when: domain_name is defined and domain_name != ""
    
    - name: Self-signed
      when: domain_name is not defined or domain_name == ""
```
